spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**, /auth/**
          filters:
            - StripPrefix=1

        - id: patient-location-service
          uri: http://localhost:5000
          predicates:
            - Path=/api/location/**
          filters:
            - StripPrefix=1
            - RewritePath=/api/location/(?<segment>.*), /$\{segment}

        - id: health-data-service
          uri: lb://HEALTH-DATA-SERVICE
          predicates:
            - Path=/api/health/**
          filters:
            - StripPrefix=1

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=1

        - id: hallway-detection-service
          uri: lb://HALLWAY-DETECTION-SERVICE
          predicates:
            - Path=/api/hallway/**
          filters:
            - StripPrefix=1